services:
  user-service:
    build: ./user-service
    container_name: user-service
    env_file: ./user-service/.env.docker
    ports:
      - "8000:8000"

  task-service:
    build: ./task-service
    container_name: task-service
    env_file: ./task-service/.env.docker
    ports:
      - "8001:8001"

  job-service:
    build: ./job-service
    container_name: job-service
    env_file: ./job-service/.env.docker
    ports:
      - "8002:8002"

  import-service:
    build: ./import-service
    container_name: import-service
    env_file: ./import-service/.env.docker
    ports:
      - "8003:8003"

networks:
  default:
    name: micro-net
