apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
data:
  NODE_ENV: "production"
  PORT: "8001"
  USER_SERVICE_URL: "http://user-service:8000"
  JOB_SERVICE_URL: "http://job-service:8002"
  IMPORT_SERVICE_URL: "http://import-service:8003"
