apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-config
data:
  PORT: "8002"
  USER_SERVICE_URL: "http://user-service:8000"
  TASK_SERVICE_URL: "http://task-service:8001"
  IMPORT_SERVICE_URL: "http://import-service:8003"
