apiVersion: v1
kind: ConfigMap
metadata:
  name: import-service-config
data:
  NODE_ENV: "production"
  PORT: "8003"
  USER_SERVICE_URL: "http://user-service:8000"
  TASK_SERVICE_URL: "http://task-service:8001"
  JOB_SERVICE_URL: "http://job-service:8002"
