apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-service
  namespace: dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: import-service
  template:
    metadata:
      labels:
        app: import-service
    spec:
      containers:
        - name: import-service
          image: 964474461010.dkr.ecr.ap-south-1.amazonaws.com/microservices-backend:import-service
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: import-service-config
            - secretRef:
                name: import-service-secret
